DROP TABLE IF EXISTS PPP.MaterialClasses;
CREATE TABLE PPP.MaterialClasses
(
    PIC    VARCHAR(40) NOT NULL,
    Material    VARCHAR(20) NOT NULL PRIMARY KEY
);

DROP TABLE IF EXISTS PPP.MonosCategory;
CREATE TABLE PPP.MonosCategory
(
    MaterialID    VARCHAR(20) NOT NULL PRIMARY KEY,
    CATEGORY    VARCHAR(100) NOT NULL
);